sudo: false
dist: trusty
language: python

cache: pip

python:
  - 3.5

addons:
  postgresql: 9.6
  apt:
    packages:
    - postgresql-9.6-postgis-2.3

install:
  - pip install -r requirements.txt -r requirements-dev.txt

before_script:
  - psql -c 'create database aggregaatori;' -U postgres
  - psql -U postgres -c "create extension postgis"

script:
  - flake8
  - pytest -ra -vvv --cov=.
  - isort -c

after_success: codecov

env:
  - SECRET_KEY=topsecret123
  - EMAIL_FROM_NAME="John Doe"
  - EMAIL_FROM_ADDRESS="john.doe@example.org"

  - EMAIL_AUTH_NAME="messaging"
  - EMAIL_AUTH_PASS="messaging"

  - TUNNISTAMO_URL='http://localhost/'
