sudo: false
language: python

cache: pip

python:
  - "3.6"
  - "nightly"

install:
  - pip install -r requirements.txt -r requirements-dev.txt

script:
  - flake8
  - pytest -ra -vvv --cov=.
  - isort -c

after_success: codecov
