# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-21 09:42
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, verbose_name='URL')),
                ('location', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326, verbose_name='Location')),
            ],
            options={
                'verbose_name_plural': 'Stories',
                'verbose_name': 'Story',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='StoryTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('text', models.TextField(blank=True, verbose_name='Text')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='stories.Story')),
            ],
            options={
                'default_permissions': (),
                'db_tablespace': '',
                'verbose_name': 'Story Translation',
                'db_table': 'stories_story_translation',
                'managed': True,
            },
        ),
        migrations.AlterUniqueTogether(
            name='storytranslation',
            unique_together=set([('language_code', 'master')]),
        ),
    ]
