# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-27 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_add_external_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='url',
        ),
        migrations.AddField(
            model_name='storytranslation',
            name='url',
            field=models.URLField(blank=True, verbose_name='URL'),
        ),
    ]
