# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-31 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_unique_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='storytranslation',
            name='short_text',
            field=models.TextField(blank=True, verbose_name='Short text'),
        ),
        migrations.AlterField(
            model_name='story',
            name='external_id',
            field=models.CharField(default=None, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
