# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-02 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0005_add_short_text_remove_external_id_null_and_blank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storytranslation',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
    ]
