# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-02 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0006_increase_title_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yso', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Keywords',
                'verbose_name': 'Keyword',
            },
        ),
    ]
