# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-02 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0007_add_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='stories', to='stories.Keyword'),
        ),
    ]
