# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-04 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0009_story_location_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
