# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-04 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0010_story_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='ocd_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
