# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-14 09:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0011_story_ocd_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='location_id',
        ),
    ]
