# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-14 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0012_remove_story_location_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storytranslation',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title'),
        ),
    ]
