# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-17 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0013_title_can_be_blank'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='type',
            field=models.CharField(default='Create', max_length=32),
            preserve_default=False,
        ),
    ]
