# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-17 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('munigeo', '0003_add_modified_time_to_address_and_street'),
        ('stories', '0014_story_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='location',
        ),
        migrations.AddField(
            model_name='story',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='stories', to='munigeo.AdministrativeDivision'),
        ),
    ]
