# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-29 07:41
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0016_actor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='ocd_id',
        ),
        migrations.RemoveField(
            model_name='storytranslation',
            name='short_text',
        ),
        migrations.RemoveField(
            model_name='storytranslation',
            name='text',
        ),
        migrations.RemoveField(
            model_name='storytranslation',
            name='title',
        ),
        migrations.AddField(
            model_name='story',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stories.Actor'),
        ),
        migrations.AddField(
            model_name='story',
            name='generator',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='geometry',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='story',
            name='json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='published',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storytranslation',
            name='content',
            field=models.TextField(blank=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='storytranslation',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='storytranslation',
            name='summary',
            field=models.TextField(blank=True, verbose_name='Summary'),
        ),
        migrations.AlterField(
            model_name='story',
            name='external_id',
            field=models.CharField(max_length=255),
        ),
    ]
