# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-01 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0019_change_actor_external_id_verbose_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importer', models.CharField(blank=True, max_length=255)),
                ('import_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
